version: '3.7'

services:
  web:
    build: backend
    volumes:
      - ./backend:/usr/src/app/
      - ./api:/usr/src/api
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: "development"
    command: flask run --host=0.0.0.0 --cert=adhoc

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
      - ./api:/usr/src/api
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - web
    command: yarn start
